<?php

if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'home',
        'title' => 'home',
        'fields' => array (
            array (
                'key' => 'field_5a16868b53641',
                'label' => 'Titre',
                'name' => 'titre',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a1686a453642',
                'label' => 'Sous titre',
                'name' => 'sous_titre',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a1686b153643',
                'label' => 'Image Landing',
                'name' => 'image_landing',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5a1686e953644',
                'label' => 'section 1 - img',
                'name' => 'section_1_-_img',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5a16870f53645',
                'label' => 'Section 1 - titre',
                'name' => 'section_1_-_titre',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a16872353646',
                'label' => 'Section 1 - content ',
                'name' => 'section_1_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a200a54d0dc4',
                'label' => 'Section 2 - img',
                'name' => 'section_2_-_img',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5a200a1b71576',
                'label' => 'Section 2 - titre',
                'name' => 'section_2_-_titre',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a200a3b71577',
                'label' => 'Section 2 - content',
                'name' => 'section_2_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a200a863fd21',
                'label' => 'Section 3 - img',
                'name' => 'section_3_-_img',
                'type' => 'image',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
            ),
            array (
                'key' => 'field_5a200a993fd22',
                'label' => 'Section 3 - titre',
                'name' => 'section_3_-_titre',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a200aa83fd23',
                'label' => 'Section 3 - content',
                'name' => 'section_3_-_content',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_5a200b244f22a',
                'label' => 'Video home',
                'name' => 'video_home',
                'type' => 'file',
                'save_format' => 'object',
                'library' => 'all',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page',
                    'operator' => '==',
                    'value' => '20',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'no_box',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
}